#!/bin/bash

echo "🚀 MyLocal Connect Deployment Guide"
echo "===================================="
echo ""

echo "📋 Pre-deployment Checklist:"
echo "1. ✅ MongoDB Atlas cluster created and configured"
echo "2. ✅ Database user created with read/write permissions"
echo "3. ✅ Network access configured (0.0.0.0/0 for deployment)"
echo "4. ✅ Connection string obtained"
echo ""

echo "🔧 Backend Deployment on Render:"
echo "1. Go to https://render.com and sign up/login"
echo "2. Click 'New' → 'Web Service'"
echo "3. Connect your GitHub repository"
echo "4. Configure the service:"
echo "   - Name: mylocal-connect-backend"
echo "   - Environment: Node"
echo "   - Build Command: cd server && npm install"
echo "   - Start Command: cd server && npm start"
echo "   - Auto-Deploy: Yes"
echo ""

echo "📱 Frontend Deployment on Render:"
echo "1. Click 'New' → 'Static Site'"
echo "2. Connect your GitHub repository"
echo "3. Configure the service:"
echo "   - Name: mylocal-connect-frontend"
echo "   - Build Command: cd client && npm install && npm run build"
echo "   - Publish Directory: client/dist"
echo "   - Auto-Deploy: Yes"
echo ""

echo "🔐 Environment Variables to set on Render (Backend):"
echo "NODE_ENV=production"
echo "PORT=10000"
echo "MONGODB_URI=<your-mongodb-atlas-connection-string>"
echo "JWT_SECRET=<generate-a-strong-secret>"
echo "CLIENT_URL=<your-frontend-render-url>"
echo "SESSION_SECRET=<generate-a-strong-session-secret>"
echo ""

echo "🔐 Environment Variables to set on Render (Frontend):"
echo "VITE_API_URL=<your-backend-render-url>/api"
echo "VITE_APP_NAME=MyLocal Connect"
echo "VITE_APP_VERSION=1.0.0"
echo ""

echo "⚠️  Important Notes:"
echo "- Replace all placeholder values with actual values"
echo "- Generate strong secrets for JWT_SECRET and SESSION_SECRET"
echo "- Ensure CORS is properly configured for your frontend URL"
echo "- Test thoroughly after deployment"
echo ""

echo "🎉 After deployment, your app will be available at:"
echo "Frontend: https://your-app-name.onrender.com"
echo "Backend API: https://your-backend-name.onrender.com/api"
